# Generated by Django 3.2.23 on 2024-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='description',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
