# Generated by Django 3.2.23 on 2024-02-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_data_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default=' ', max_length=500)),
                ('image', models.ImageField(default=' ', upload_to='images/')),
            ],
        ),
    ]
