# Generated by Django 3.2.23 on 2024-02-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='image',
            field=models.ImageField(default=' ', upload_to='images1/'),
        ),
    ]
