# Generated by Django 3.2.23 on 2024-02-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_contact_mnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('experiance', models.CharField(max_length=20)),
                ('Rskill', models.CharField(max_length=100)),
            ],
        ),
    ]
