# Generated by Django 3.2.23 on 2024-02-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(default=' ', upload_to='resumes/'),
        ),
    ]
